org: dking949
app: aws-fpl-transfer-abuse-api
service: aws-fpl-transfer-abuse-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  getAllData:
    handler: transferNightmares.getAllData
    events:
      - httpApi:
          path: /
          method: get
    timeout: 20
  getTransfers:
    handler: transferNightmares.getTransfersApi
    environment: 
      FPL_LOGIN: ${ssm(us-east-1):FPL_LOGIN}
      FPL_PWD: ${ssm(us-east-1):FPL_PWD}
    events:
      - httpApi:
          path: /transfers
          method: get
    timeout: 15
  getDifferentials:
    handler: transferNightmares.getDifferentialsApi
    events:
      - httpApi:
          path: /differentials
          method: get
    timeout: 15
  getCaptains:
    handler: transferNightmares.getCaptainsApi
    events:
      - httpApi:
          path: /captains
          method: get
    timeout: 15

plugins:
  - serverless-python-requirements
  - serverless-offline
custom:
  pythonRequirements:
    dockerizePip: non-linux